name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write # To push Docker images to ghcr.io

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
      - name: Validate krew-index manifest
        run: |
          set -euo pipefail
          KREW_VERSION=v0.4.4
          pushd "$(mktemp -d)"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${KREW_VERSION}/krew.yaml"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${KREW_VERSION}/krew-linux_amd64.tar.gz"
          tar zxvf krew-linux_amd64.tar.gz
          ./krew-linux_amd64 install --manifest=krew.yaml --archive=krew-linux_amd64.tar.gz
          popd
          export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
          export TAG=$(curl -sL https://github.com/boz/kail/releases/latest -H "Accept: application/json" | jq -r .tag_name)
          ls -la ./.krew/tail.yaml          
          docker run --rm -v ./.krew/tail.yaml:/tmp/template-file.yaml ghcr.io/rajatjindal/krew-release-bot:latest krew-release-bot template --tag ${TAG} --template-file /tmp/template-file.yaml 1>/tmp/tail.yaml
          go install sigs.k8s.io/krew/cmd/validate-krew-manifest@latest
          ~/go/bin/validate-krew-manifest -manifest /tmp/tail.yaml
      - name: Update krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
        with:
          krew_template_file: .krew/tail.yaml
